# .github/workflows/scheduled-builds.yml
name: Powerbomb Harvestor Bot

on:
  schedule:
    # Runs "1 am and 1 pm UTC" (see https://crontab.guru)
    - cron: '0 1,13 * * *'
jobs:
  build:
    name: Powerbomb Harvest
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        # Hit the webhook endpoint to rebuild  from the "main" branch
        run: curl -X GET https://powerbomb-dev.netlify.app/api/powerbomb
